# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shaft_dialog.ui'
#
# Created: Fri Jul 18 20:23:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(818, 556)
        self.textBrowser_title = QtGui.QTextBrowser(MainDialog)
        self.textBrowser_title.setGeometry(QtCore.QRect(10, 10, 801, 121))
        self.textBrowser_title.setObjectName("textBrowser_title")
        self.progressBar = QtGui.QProgressBar(MainDialog)
        self.progressBar.setGeometry(QtCore.QRect(110, 520, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtGui.QGroupBox(MainDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 391, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_shaft_diam = QtGui.QLabel(self.groupBox)
        self.label_shaft_diam.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label_shaft_diam.setObjectName("label_shaft_diam")
        self.label_elastic_mod = QtGui.QLabel(self.groupBox)
        self.label_elastic_mod.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_elastic_mod.setObjectName("label_elastic_mod")
        self.lineEdit_elastic_mod = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_elastic_mod.setGeometry(QtCore.QRect(100, 60, 131, 20))
        self.lineEdit_elastic_mod.setText("")
        self.lineEdit_elastic_mod.setObjectName("lineEdit_elastic_mod")
        self.lineedit_shaft_diam = QtGui.QLineEdit(self.groupBox)
        self.lineedit_shaft_diam.setGeometry(QtCore.QRect(100, 30, 131, 20))
        self.lineedit_shaft_diam.setText("")
        self.lineedit_shaft_diam.setObjectName("lineedit_shaft_diam")
        self.label_material_type = QtGui.QLabel(self.groupBox)
        self.label_material_type.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_material_type.setObjectName("label_material_type")
        self.combo_material_type = QtGui.QComboBox(self.groupBox)
        self.combo_material_type.setGeometry(QtCore.QRect(100, 120, 71, 22))
        self.combo_material_type.setObjectName("combo_material_type")
        self.combo_material_type.addItem("")
        self.combo_material_type.addItem("")
        self.label_factor_safety = QtGui.QLabel(self.groupBox)
        self.label_factor_safety.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.label_factor_safety.setObjectName("label_factor_safety")
        self.spinbox_safety_factor = QtGui.QSpinBox(self.groupBox)
        self.spinbox_safety_factor.setGeometry(QtCore.QRect(100, 150, 42, 22))
        self.spinbox_safety_factor.setPrefix("")
        self.spinbox_safety_factor.setMinimum(1)
        self.spinbox_safety_factor.setObjectName("spinbox_safety_factor")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineedit_shaft_length = QtGui.QLineEdit(self.groupBox)
        self.lineedit_shaft_length.setGeometry(QtCore.QRect(100, 90, 131, 20))
        self.lineedit_shaft_length.setText("")
        self.lineedit_shaft_length.setObjectName("lineedit_shaft_length")
        self.textBrowser = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(240, 30, 141, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 150, 61, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(310, 150, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.groupBox_2 = QtGui.QGroupBox(MainDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 140, 411, 411))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 110, 391, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_point = QtGui.QLabel(self.groupBox_3)
        self.label_point.setGeometry(QtCore.QRect(0, 20, 91, 21))
        self.label_point.setObjectName("label_point")
        self.label_deflection_causedby = QtGui.QLabel(self.groupBox_3)
        self.label_deflection_causedby.setGeometry(QtCore.QRect(90, 20, 111, 16))
        self.label_deflection_causedby.setObjectName("label_deflection_causedby")
        self.label_deflect_coord1 = QtGui.QLabel(self.groupBox_3)
        self.label_deflect_coord1.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label_deflect_coord1.setObjectName("label_deflect_coord1")
        self.label_deflect_coord2 = QtGui.QLabel(self.groupBox_3)
        self.label_deflect_coord2.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.label_deflect_coord2.setObjectName("label_deflect_coord2")
        self.label_deflect_coord3 = QtGui.QLabel(self.groupBox_3)
        self.label_deflect_coord3.setGeometry(QtCore.QRect(10, 100, 41, 16))
        self.label_deflect_coord3.setObjectName("label_deflect_coord3")
        self.label_deflect_coord4 = QtGui.QLabel(self.groupBox_3)
        self.label_deflect_coord4.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.label_deflect_coord4.setObjectName("label_deflect_coord4")
        self.label_deflect_load1_2 = QtGui.QLabel(self.groupBox_3)
        self.label_deflect_load1_2.setGeometry(QtCore.QRect(90, 40, 46, 13))
        self.label_deflect_load1_2.setText("")
        self.label_deflect_load1_2.setObjectName("label_deflect_load1_2")
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(90, 40, 61, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 70, 61, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 100, 61, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 130, 61, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.lineedit_point1_deflection = QtGui.QLineEdit(self.groupBox_3)
        self.lineedit_point1_deflection.setGeometry(QtCore.QRect(180, 40, 201, 20))
        self.lineedit_point1_deflection.setText("")
        self.lineedit_point1_deflection.setObjectName("lineedit_point1_deflection")
        self.lineedit_point2_deflection = QtGui.QLineEdit(self.groupBox_3)
        self.lineedit_point2_deflection.setGeometry(QtCore.QRect(180, 70, 201, 20))
        self.lineedit_point2_deflection.setText("")
        self.lineedit_point2_deflection.setObjectName("lineedit_point2_deflection")
        self.lineedit_point3_deflection = QtGui.QLineEdit(self.groupBox_3)
        self.lineedit_point3_deflection.setGeometry(QtCore.QRect(180, 100, 201, 20))
        self.lineedit_point3_deflection.setText("")
        self.lineedit_point3_deflection.setObjectName("lineedit_point3_deflection")
        self.lineedit_shaft_diam_5 = QtGui.QLineEdit(self.groupBox_3)
        self.lineedit_shaft_diam_5.setGeometry(QtCore.QRect(180, 130, 201, 20))
        self.lineedit_shaft_diam_5.setText("")
        self.lineedit_shaft_diam_5.setObjectName("lineedit_shaft_diam_5")
        self.label_deflection = QtGui.QLabel(self.groupBox_3)
        self.label_deflection.setGeometry(QtCore.QRect(250, 20, 51, 16))
        self.label_deflection.setObjectName("label_deflection")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 391, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_bending_inertia = QtGui.QLabel(self.groupBox_4)
        self.label_bending_inertia.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label_bending_inertia.setObjectName("label_bending_inertia")
        self.label_bending_inertia_2 = QtGui.QLabel(self.groupBox_4)
        self.label_bending_inertia_2.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.label_bending_inertia_2.setObjectName("label_bending_inertia_2")
        self.lineedit_bendinginertia = QtGui.QLineEdit(self.groupBox_4)
        self.lineedit_bendinginertia.setGeometry(QtCore.QRect(150, 20, 231, 20))
        self.lineedit_bendinginertia.setText("")
        self.lineedit_bendinginertia.setObjectName("lineedit_bendinginertia")
        self.lineedit_torsioninertia = QtGui.QLineEdit(self.groupBox_4)
        self.lineedit_torsioninertia.setGeometry(QtCore.QRect(150, 50, 231, 20))
        self.lineedit_torsioninertia.setText("")
        self.lineedit_torsioninertia.setObjectName("lineedit_torsioninertia")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 300, 391, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_raleighs = QtGui.QLabel(self.groupBox_5)
        self.label_raleighs.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_raleighs.setObjectName("label_raleighs")
        self.label_dunkerleys = QtGui.QLabel(self.groupBox_5)
        self.label_dunkerleys.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_dunkerleys.setObjectName("label_dunkerleys")
        self.lineedit_natfreq_ral = QtGui.QLineEdit(self.groupBox_5)
        self.lineedit_natfreq_ral.setGeometry(QtCore.QRect(80, 30, 301, 20))
        self.lineedit_natfreq_ral.setText("")
        self.lineedit_natfreq_ral.setObjectName("lineedit_natfreq_ral")
        self.lineedit_natfreq_dunk = QtGui.QLineEdit(self.groupBox_5)
        self.lineedit_natfreq_dunk.setGeometry(QtCore.QRect(80, 60, 301, 20))
        self.lineedit_natfreq_dunk.setText("")
        self.lineedit_natfreq_dunk.setObjectName("lineedit_natfreq_dunk")
        self.groupbox_loads = QtGui.QGroupBox(MainDialog)
        self.groupbox_loads.setGeometry(QtCore.QRect(10, 330, 391, 181))
        self.groupbox_loads.setObjectName("groupbox_loads")
        self.label_load_1 = QtGui.QLabel(self.groupbox_loads)
        self.label_load_1.setGeometry(QtCore.QRect(20, 40, 46, 13))
        self.label_load_1.setObjectName("label_load_1")
        self.label_9 = QtGui.QLabel(self.groupbox_loads)
        self.label_9.setGeometry(QtCore.QRect(60, 10, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupbox_loads)
        self.label_10.setGeometry(QtCore.QRect(230, 10, 71, 16))
        self.label_10.setObjectName("label_10")
        self.lineedit_xcoo_load1 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_xcoo_load1.setGeometry(QtCore.QRect(60, 40, 141, 20))
        self.lineedit_xcoo_load1.setObjectName("lineedit_xcoo_load1")
        self.lineedit_massweight_load1 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_massweight_load1.setGeometry(QtCore.QRect(230, 40, 141, 20))
        self.lineedit_massweight_load1.setObjectName("lineedit_massweight_load1")
        self.lineedit_massweight_load2 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_massweight_load2.setGeometry(QtCore.QRect(230, 70, 141, 20))
        self.lineedit_massweight_load2.setObjectName("lineedit_massweight_load2")
        self.label_load_2 = QtGui.QLabel(self.groupbox_loads)
        self.label_load_2.setGeometry(QtCore.QRect(20, 70, 46, 13))
        self.label_load_2.setObjectName("label_load_2")
        self.lineedit_xcoo_load2 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_xcoo_load2.setGeometry(QtCore.QRect(60, 70, 141, 20))
        self.lineedit_xcoo_load2.setReadOnly(False)
        self.lineedit_xcoo_load2.setObjectName("lineedit_xcoo_load2")
        self.lineedit_massweight_load3 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_massweight_load3.setGeometry(QtCore.QRect(230, 100, 141, 20))
        self.lineedit_massweight_load3.setObjectName("lineedit_massweight_load3")
        self.label_load_3 = QtGui.QLabel(self.groupbox_loads)
        self.label_load_3.setGeometry(QtCore.QRect(20, 100, 46, 13))
        self.label_load_3.setObjectName("label_load_3")
        self.lineedit_xcoo_load3 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_xcoo_load3.setGeometry(QtCore.QRect(60, 100, 141, 20))
        self.lineedit_xcoo_load3.setObjectName("lineedit_xcoo_load3")
        self.lineedit_massweight_load4 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_massweight_load4.setGeometry(QtCore.QRect(230, 130, 141, 20))
        self.lineedit_massweight_load4.setObjectName("lineedit_massweight_load4")
        self.label_load_4 = QtGui.QLabel(self.groupbox_loads)
        self.label_load_4.setGeometry(QtCore.QRect(20, 130, 46, 13))
        self.label_load_4.setObjectName("label_load_4")
        self.lineedit_xcoo_load4 = QtGui.QLineEdit(self.groupbox_loads)
        self.lineedit_xcoo_load4.setGeometry(QtCore.QRect(60, 130, 141, 20))
        self.lineedit_xcoo_load4.setObjectName("lineedit_xcoo_load4")
        self.view_coord = QtGui.QToolButton(self.groupbox_loads)
        self.view_coord.setGeometry(QtCore.QRect(230, 160, 151, 19))
        self.view_coord.setObjectName("view_coord")
        self.label = QtGui.QLabel(MainDialog)
        self.label.setGeometry(QtCore.QRect(10, 520, 71, 16))
        self.label.setObjectName("label")
        self.calculate = QtGui.QPushButton(MainDialog)
        self.calculate.setGeometry(QtCore.QRect(320, 520, 75, 23))
        self.calculate.setObjectName("calculate")

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)
        MainDialog.setTabOrder(self.lineedit_shaft_diam, self.lineEdit_elastic_mod)
        MainDialog.setTabOrder(self.lineEdit_elastic_mod, self.lineedit_shaft_length)
        MainDialog.setTabOrder(self.lineedit_shaft_length, self.combo_material_type)
        MainDialog.setTabOrder(self.combo_material_type, self.spinbox_safety_factor)
        MainDialog.setTabOrder(self.spinbox_safety_factor, self.comboBox_5)
        MainDialog.setTabOrder(self.comboBox_5, self.lineedit_xcoo_load1)
        MainDialog.setTabOrder(self.lineedit_xcoo_load1, self.lineedit_massweight_load1)
        MainDialog.setTabOrder(self.lineedit_massweight_load1, self.lineedit_xcoo_load2)
        MainDialog.setTabOrder(self.lineedit_xcoo_load2, self.lineedit_massweight_load2)
        MainDialog.setTabOrder(self.lineedit_massweight_load2, self.lineedit_xcoo_load3)
        MainDialog.setTabOrder(self.lineedit_xcoo_load3, self.lineedit_massweight_load3)
        MainDialog.setTabOrder(self.lineedit_massweight_load3, self.lineedit_xcoo_load4)
        MainDialog.setTabOrder(self.lineedit_xcoo_load4, self.lineedit_massweight_load4)
        MainDialog.setTabOrder(self.lineedit_massweight_load4, self.view_coord)
        MainDialog.setTabOrder(self.view_coord, self.calculate)
        MainDialog.setTabOrder(self.calculate, self.lineedit_bendinginertia)
        MainDialog.setTabOrder(self.lineedit_bendinginertia, self.lineedit_torsioninertia)
        MainDialog.setTabOrder(self.lineedit_torsioninertia, self.comboBox)
        MainDialog.setTabOrder(self.comboBox, self.lineedit_point1_deflection)
        MainDialog.setTabOrder(self.lineedit_point1_deflection, self.comboBox_2)
        MainDialog.setTabOrder(self.comboBox_2, self.lineedit_point2_deflection)
        MainDialog.setTabOrder(self.lineedit_point2_deflection, self.comboBox_3)
        MainDialog.setTabOrder(self.comboBox_3, self.lineedit_point3_deflection)
        MainDialog.setTabOrder(self.lineedit_point3_deflection, self.comboBox_4)
        MainDialog.setTabOrder(self.comboBox_4, self.lineedit_shaft_diam_5)
        MainDialog.setTabOrder(self.lineedit_shaft_diam_5, self.lineedit_natfreq_ral)
        MainDialog.setTabOrder(self.lineedit_natfreq_ral, self.lineedit_natfreq_dunk)
        MainDialog.setTabOrder(self.lineedit_natfreq_dunk, self.textBrowser_title)
        MainDialog.setTabOrder(self.textBrowser_title, self.textBrowser)

    def retranslateUi(self, MainDialog):
        MainDialog.setWindowTitle(QtGui.QApplication.translate("MainDialog", "Shafts Solver - Joe Gregory", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_title.setHtml(QtGui.QApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Shaft Problems Solver </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Designed for Shigley\'s Mechanical Engineering Design 9th Ed. Chapter 7 &quot;Shafts and Shaft Components&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">FINAL CLASS PROJECT 409</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">By</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Joseph E. Gregory</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainDialog", "Problem Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_shaft_diam.setText(QtGui.QApplication.translate("MainDialog", "Shaft\'s Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_elastic_mod.setText(QtGui.QApplication.translate("MainDialog", "Elastic Modulus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_material_type.setText(QtGui.QApplication.translate("MainDialog", "Material Type", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_material_type.setItemText(0, QtGui.QApplication.translate("MainDialog", "Ductile", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_material_type.setItemText(1, QtGui.QApplication.translate("MainDialog", "Brittle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_factor_safety.setText(QtGui.QApplication.translate("MainDialog", "Factor of Safety", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainDialog", "Shaft\'s Length", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setProperty("placeholderText", QtGui.QApplication.translate("MainDialog", "Hello, the program will use this space to give you any messages for things that might need your attention!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainDialog", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainDialog", "Global Units", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(0, QtGui.QApplication.translate("MainDialog", "SI", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(1, QtGui.QApplication.translate("MainDialog", "EN", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainDialog", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainDialog", "Deflections", None, QtGui.QApplication.UnicodeUTF8))
        self.label_point.setText(QtGui.QApplication.translate("MainDialog", "Coordinates at...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deflection_causedby.setText(QtGui.QApplication.translate("MainDialog", "Deflection caused by...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deflect_coord1.setText(QtGui.QApplication.translate("MainDialog", "Load 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deflect_coord2.setText(QtGui.QApplication.translate("MainDialog", "Load 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deflect_coord3.setText(QtGui.QApplication.translate("MainDialog", "Load 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deflect_coord4.setText(QtGui.QApplication.translate("MainDialog", "Load 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainDialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainDialog", "Load 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainDialog", "Load 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainDialog", "Load 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainDialog", "Load 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainDialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainDialog", "Load 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainDialog", "Load 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("MainDialog", "Load 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("MainDialog", "Load 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("MainDialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("MainDialog", "Load 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("MainDialog", "Load 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(3, QtGui.QApplication.translate("MainDialog", "Load 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(4, QtGui.QApplication.translate("MainDialog", "Load 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(0, QtGui.QApplication.translate("MainDialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(1, QtGui.QApplication.translate("MainDialog", "Load 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(2, QtGui.QApplication.translate("MainDialog", "Load 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(3, QtGui.QApplication.translate("MainDialog", "Load 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(4, QtGui.QApplication.translate("MainDialog", "Load 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_deflection.setText(QtGui.QApplication.translate("MainDialog", "Deflection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainDialog", "Moments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bending_inertia.setText(QtGui.QApplication.translate("MainDialog", "Bending Moment of Inertia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bending_inertia_2.setText(QtGui.QApplication.translate("MainDialog", "Torsion Moment of Inertia", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainDialog", "Bending Natural Frequencies", None, QtGui.QApplication.UnicodeUTF8))
        self.label_raleighs.setText(QtGui.QApplication.translate("MainDialog", "Raleigh\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dunkerleys.setText(QtGui.QApplication.translate("MainDialog", "Dunkerley\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_loads.setTitle(QtGui.QApplication.translate("MainDialog", "Loads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_load_1.setText(QtGui.QApplication.translate("MainDialog", "Load 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainDialog", "X Coordinate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainDialog", "Mass/Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_load_2.setText(QtGui.QApplication.translate("MainDialog", "Load 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_load_3.setText(QtGui.QApplication.translate("MainDialog", "Load 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_load_4.setText(QtGui.QApplication.translate("MainDialog", "Load 4", None, QtGui.QApplication.UnicodeUTF8))
        self.view_coord.setText(QtGui.QApplication.translate("MainDialog", "View Coordinate System...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainDialog", "Problem Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate.setText(QtGui.QApplication.translate("MainDialog", "Calculate", None, QtGui.QApplication.UnicodeUTF8))

